Feature/add imput to search
InsanityPrision/music-oasis pull request #11
Opened 2024-10-10 18:25 UTC by InsanityPrision

- Change div for icon searh to imput 
- Put color in body and inherit into text of icons

2024-10-10 19:00 UTC, the-refactor-project commented on public/index.html
> +    <imput class="icon"><img src="images/search.svg" alt="Search icon"> <span class="icon-text">Search</span></imput>
¿Qué etiqueta HTML es `imput`?

2024-10-10 21:10 UTC, arodrigue96 requested changes
La línea 19 del código index.html no es correcta

2024-10-11 04:49 UTC, the-refactor-project commented
> La línea 19 del código index.html no es correcta

Los comentarios sobre una línea concreta de un archivo concreto no se hacen aquí, y "no es correcta" no da ninguna información de qué hay que revisar.

2024-10-11 07:28 UTC, arodrigue96 approved these changes

2024-10-11 07:29 UTC, merged

2024-10-12 12:59 UTC, InsanityPrision commented on public/index.html
> +    <imput class="icon"><img src="images/search.svg" alt="Search icon"> <span class="icon-text">Search</span></imput>
Cambiado a input

2024-10-12 15:59 UTC, InsanityPrision commented
Entendido, los comentarios se harán mejor y con más info

2024-10-12 16:21 UTC, arodrigue96 commented
Entendido, seremos más específicos