Bug fix input on search change to a button
InsanityPrision/music-oasis pull request #15
Opened 2024-10-11 15:19 UTC by InsanityPrision

- Change input search to a button

2024-10-11 15:34 UTC, arodrigue96 approved these changes, later dismissed

2024-10-11 15:44 UTC, arodrigue96 submitted a review, later dismissed

2024-10-12 10:47 UTC, arodrigue96 approved these changes

2024-10-12 12:40 UTC, the-refactor-project requested changes

2024-10-12 12:40 UTC, the-refactor-project commented on public/styles/styles.css
> +  font-family: Montserrat, "sans serif";
Esto es incorrecto, no hay ninguna familia de tipografías que se llame "sans serif".

2024-10-12 12:52 UTC, InsanityPrision commented on public/styles/styles.css
> +  font-family: Montserrat, "sans serif";
El validador de css saltaba un warning  de que no estaba entre comillas al ser dos palabras

2024-10-12 12:52 UTC, arodrigue96 requested changes
Hay que arreglar la font-family a Montserrat, sans-serif

2024-10-12 12:53 UTC, arodrigue96 commented on public/styles/styles.css
> +  font-family: Montserrat, "sans serif";
@InsanityPrision es sans-serif

2024-10-12 13:17 UTC, InsanityPrision commented on public/styles/styles.css
> +  font-family: Montserrat, "sans serif";
Vale vale, entendido y cambiado

2024-10-12 13:43 UTC, arodrigue96 approved these changes, later dismissed

2024-10-12 13:59 UTC, arodrigue96 requested changes
Check para confirmar si el selector está bien escrito.

2024-10-12 13:59 UTC, arodrigue96 commented on public/styles/styles.css
> +  > :nth-child(1) {
¿Está bien escrito este selector? Has cerrado la llave de body en la línea 26

2024-10-12 15:32 UTC, InsanityPrision commented on public/styles/styles.css
> +  > :nth-child(1) {
Esta bien cerrado

2024-10-12 15:35 UTC, arodrigue96 approved these changes, later dismissed

2024-10-12 16:36 UTC, arodrigue96 approved these changes

2024-10-12 16:37 UTC, merged