Feature/central body layout
InsanityPrision/music-oasis pull request #4
Opened 2024-10-09 21:05 UTC by arodrigue96

- Create  main container for body layout in mobile and desktop version

2024-10-09 21:17 UTC, InsanityPrision requested changes
Cambios a aplicar

2024-10-09 21:17 UTC, InsanityPrision commented on public/styles/styles.css
> +  @media (width > 600px) {
Podemos poner un = aquí

2024-10-09 21:26 UTC, InsanityPrision approved these changes

2024-10-09 21:27 UTC, merged

2024-10-12 16:28 UTC, arodrigue96 commented on public/styles/styles.css
> +  @media (width > 600px) {
Cambio aplicado