Change cart icon to a button
InsanityPrision/music-oasis pull request #9
Opened 2024-10-10 16:21 UTC by InsanityPrision

- Change div to a button in cart icon
- Add styles in button

2024-10-10 17:09 UTC, arodrigue96 requested changes
Únicamente hay que sacar la clase que te he comentado

2024-10-10 17:09 UTC, arodrigue96 commented on public/index.html
> +    <div class="icon"><img class="incon-img" src="images/search.svg" alt="Search icon"> <span
Has puesto la classe "incon-img" y no la estás usando.

2024-10-10 17:09 UTC, arodrigue96 commented on public/index.html
> +    <div class="logo"><img class="incon-img" src="images/symbol.svg" alt="Music Oasis logo"><span class="brand-text">
Aqui igual

2024-10-10 17:09 UTC, arodrigue96 commented on public/index.html
> +    <a href="#" class="icon-cart"><img class="incon-img" src="images/cart.svg" alt="Shopping cart icon"> <span
Lo mismo lo de la clase

2024-10-10 17:11 UTC, InsanityPrision commented on public/index.html
> +    <div class="icon"><img class="incon-img" src="images/search.svg" alt="Search icon"> <span
Verdad, ya no se usan, las quitaré ahora

2024-10-10 17:12 UTC, arodrigue96 approved these changes

2024-10-10 17:12 UTC, merged

2024-10-10 19:04 UTC, the-refactor-project commented on public/index.html
> +    <div class="logo"><img class="incon-img" src="images/symbol.svg" alt="Music Oasis logo"><span class="brand-text">
@InsanityPrision hay que dar feedback a todos los mensajes de review que te escriban.

2024-10-10 19:04 UTC, the-refactor-project commented on public/index.html
> +    <a href="#" class="icon-cart"><img class="incon-img" src="images/cart.svg" alt="Shopping cart icon"> <span
@InsanityPrision hay que dar feedback a todos los mensajes de review que te escriban.

2024-10-10 19:04 UTC, the-refactor-project commented
> Únicamente hay que sacar la clase que te he comentado

Quien lea esto no tiene ni idea de lo que estáis hablando.

2024-10-10 19:05 UTC, the-refactor-project commented
¿Por qué la feature y la PR se llaman "Cambiar icono cart a button" y no hay ningún button en ningún sitio?

2024-10-12 12:56 UTC, InsanityPrision commented on public/index.html
> +    <div class="logo"><img class="incon-img" src="images/symbol.svg" alt="Music Oasis logo"><span class="brand-text">
Clase quitada

2024-10-12 12:56 UTC, InsanityPrision commented on public/index.html
> +    <a href="#" class="icon-cart"><img class="incon-img" src="images/cart.svg" alt="Shopping cart icon"> <span
Clase quitada

2024-10-12 12:59 UTC, InsanityPrision commented
Se ha puesto como un botón y se puso como un ancor, ahora eso ha sido corregido y cambiado a un button